import type { ChordShape } from '@/music';

/** Standard open/barre voicings for the beginner chord library. */
export const CHORDS: readonly ChordShape[] = [
  {
    id: 'E-open',
    name: 'E',
    root: 4,
    quality: 'maj',
    baseFret: 1,
    frets: [0, 2, 2, 1, 0, 0],
    fingers: [null, 2, 3, 1, null, null],
    difficulty: 1,
  },
  {
    id: 'Am-open',
    name: 'Am',
    root: 9,
    quality: 'min',
    baseFret: 1,
    frets: [null, 0, 2, 2, 1, 0],
    fingers: [null, null, 2, 3, 1, null],
    difficulty: 1,
  },
  {
    id: 'D-open',
    name: 'D',
    root: 2,
    quality: 'maj',
    baseFret: 1,
    frets: [null, null, 0, 2, 3, 2],
    fingers: [null, null, null, 1, 3, 2],
    difficulty: 1,
  },
  {
    id: 'G-open',
    name: 'G',
    root: 7,
    quality: 'maj',
    baseFret: 1,
    frets: [3, 2, 0, 0, 0, 3],
    fingers: [3, 2, null, null, null, 4],
    difficulty: 2,
  },
  {
    id: 'C-open',
    name: 'C',
    root: 0,
    quality: 'maj',
    baseFret: 1,
    frets: [null, 3, 2, 0, 1, 0],
    fingers: [null, 3, 2, null, 1, null],
    difficulty: 2,
  },
  {
    id: 'Em-open',
    name: 'Em',
    root: 4,
    quality: 'min',
    baseFret: 1,
    frets: [0, 2, 2, 0, 0, 0],
    fingers: [null, 2, 3, null, null, null],
    difficulty: 1,
  },
  {
    id: 'A-open',
    name: 'A',
    root: 9,
    quality: 'maj',
    baseFret: 1,
    frets: [null, 0, 2, 2, 2, 0],
    fingers: [null, null, 1, 2, 3, null],
    difficulty: 1,
  },
  {
    id: 'Dm-open',
    name: 'Dm',
    root: 2,
    quality: 'min',
    baseFret: 1,
    frets: [null, null, 0, 2, 3, 1],
    fingers: [null, null, null, 2, 3, 1],
    difficulty: 1,
  },
  {
    id: 'F-barre',
    name: 'F',
    root: 5,
    quality: 'maj',
    baseFret: 1,
    frets: [1, 3, 3, 2, 1, 1],
    fingers: [1, 3, 4, 2, 1, 1],
    barre: { fret: 1, fromStringIndex: 0, toStringIndex: 5 },
    difficulty: 3,
  },
];

export function getChord(id: string): ChordShape | undefined {
  return CHORDS.find((chord) => chord.id === id);
}
